url: http://viennaigelstriathlon.club/
# baseurl: /

# Site settings
title: Vienna Igels Triathlon Club
email: spam@viennaigelstriathlon.club
description: "An international Triathlon Club based in Vienna."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EE5050
  secondary: EE5050  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Member One
  pic: 1
  position: athlete
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Member Two
  pic: 2
  position: athlete
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Member Three
  pic: 3
  position: athlete
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Member Four
  pic: 3
  position: athlete
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Member Five
  pic: 3
  position: athlete
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, facebook etc.)
social:
#  - title: twitter
#    url: http://twitter.com/viennaigels

# Postal address (add as many lines as necessary)
address:
  - line: Vienna, Austria

# Build settings
markdown: kramdown
permalink: pretty
